### ISSUE TITLE
Can't compile with error: 'Dependency not allowed'

### ISSUE THREAD

**Issue by yjukaku** [strange/erlang_v8#6]
Thanks for your work on this module.
I'm trying to compile this using `make` and this is the error I'm getting after adding the `-vv` flag:

```
make[1]: Entering directory '/Users/me/myapp/deps/erlang_v8/deps/jsx'
make[1]: Leaving directory '/Users/me/myapp/deps/erlang_v8/deps/jsx'
make -C /Users/me/myapp/deps/erlang_v8/c_src
make[1]: Entering directory '/Users/me/myapp/deps/erlang_v8/c_src'
################################################################################
/usr/bin/python -u tools/mb/mb.py gen -f infra/mb/mb_config.pyl -m developer_default -b x64.release out.gn/x64.release
  
  Writing """\
  is_debug = false
  target_cpu = "x64"
  """ to /Users/me/myapp/deps/erlang_v8/build/v8/out.gn/x64.release/args.gn.
  
  /Users/me/myapp/deps/erlang_v8/build/v8/buildtools/mac/gn gen out.gn/x64.release --check
    -> returned 1
  ERROR at //gni/v8.gni:116:3: Dependency not allowed.
    executable(target_name) {
    ^------------------------
  The item //:mkpeephole
  can not depend on //build/config/sanitizers:deps
  because it is not in //build/config/sanitizers:deps's visibility list: [
    //build/config:exe_and_shlib_deps
  ]
  
  GN gen failed: 1
Traceback (most recent call last):
  File "./tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "./tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "./tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "./tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
make[1]: *** [Makefile:66: /Users/me/myapp/deps/erlang_v8/c_src/../priv/libv8_libbase.so] Error 1
make[1]: Leaving directory '/Users/me/myapp/deps/erlang_v8/c_src'
make: *** [erlang.mk:5841: app-c_src] Error 2
```

Any suggestions? Thanks again.

**Comment by strange** [comment]
Hi!

Please give me some more detail about your system (hardware, os etc).

Thanks!

- Gustaf

**Comment by yjukaku** [comment]
I'm not on that machine right now, but it's a Macbook Pro running OS X 10.11 El Capitan

**Comment by yjukaku** [comment]
If there's a specific command you want me to run to get more detailed information, please let me know. 👍
